[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "python -m venv .venv",
  ". .venv/bin/activate && pip install --upgrade pip",
  ". .venv/bin/activate && pip install -r biblioteca/requirements.txt"
]

[start]
cmd = "cd biblioteca && ../.venv/bin/python manage.py migrate && ../.venv/bin/python manage.py runserver 0.0.0.0:$PORT"
