[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r biblioteca/requirements.txt"
]

[start]
cmd = "cd biblioteca && python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"
