# Generated by Django 6.0.4 on 2026-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_emprestimo_devolvido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
